-- ============================================================
-- Proyecto: La Esquinita del Pan | Grupo 4
--Dilan Tenorio Rojas
--CALVO HERRA LUIS ESTEBAN
--CARVAJAL FLORES BRYAN ALBERTO
--CORDERO GARCIA BRYAN STEVEN
--VELASQUEZ MORALES EDUARDO JOSE
-- ============================================================
-- Tabla Roles
CREATE TABLE FIDE_Roles_TB (
    ID_Rol NUMBER(10) PRIMARY KEY,
    Nombre_Rol NVARCHAR2(100) NOT NULL
);
CREATE OR REPLACE TRIGGER TRG_ROLES_BI
BEFORE INSERT ON FIDE_Roles_TB FOR EACH ROW
BEGIN SELECT SEQ_ROLES.NEXTVAL INTO :NEW.ID_Rol FROM DUAL; END;
/

-- Tabla Tipo
CREATE TABLE FIDE_Tipo_TB (
    ID_Tipo NUMBER(10) PRIMARY KEY,
    Nombre_Tipo NVARCHAR2(100) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_TIPO_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_TIPO_BI
BEFORE INSERT ON FIDE_Tipo_TB FOR EACH ROW
BEGIN SELECT SEQ_TIPO.NEXTVAL INTO :NEW.ID_Tipo FROM DUAL; END;
/

-- Tabla Categorias
CREATE TABLE FIDE_Categorias_TB (
    ID_Categoria NUMBER(10) PRIMARY KEY,
    Nombre_Categoria NVARCHAR2(100) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_CAT_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_CATEGORIAS_BI
BEFORE INSERT ON FIDE_Categorias_TB FOR EACH ROW
BEGIN SELECT SEQ_CATEGORIAS.NEXTVAL INTO :NEW.ID_Categoria FROM DUAL; END;
/

-- Tabla Unidades_Medidas
CREATE TABLE FIDE_Unidades_Medidas_TB (
    ID_Unidad_Medida NUMBER(10) PRIMARY KEY,
    Nombre_Medida NVARCHAR2(100) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_UNIDAD_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_UNIDADES_BI
BEFORE INSERT ON FIDE_Unidades_Medidas_TB FOR EACH ROW
BEGIN SELECT SEQ_UNIDADES.NEXTVAL INTO :NEW.ID_Unidad_Medida FROM DUAL; END;
/

-- Tabla Metodos_Pago
CREATE TABLE FIDE_Metodos_Pago_TB (
    ID_Metodo_Pago NUMBER(10) PRIMARY KEY,
    Nombre_Metodo NVARCHAR2(100) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_METODO_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_METODOS_BI
BEFORE INSERT ON FIDE_Metodos_Pago_TB FOR EACH ROW
BEGIN SELECT SEQ_METODOS_PAGO.NEXTVAL INTO :NEW.ID_Metodo_Pago FROM DUAL; END;
/

-- Tabla Referencia_Tabla
CREATE TABLE FIDE_Referencia_Tabla_TB (
    ID_Referencia_Tabla NUMBER(10) PRIMARY KEY,
    Nombre_Referencia NVARCHAR2(100) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_REF_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_REFERENCIA_BI
BEFORE INSERT ON FIDE_Referencia_Tabla_TB FOR EACH ROW
BEGIN SELECT SEQ_REFERENCIA.NEXTVAL INTO :NEW.ID_Referencia_Tabla FROM DUAL; END;
/

-- Tabla Proveedores
CREATE TABLE FIDE_Proveedores_TB (
    ID_Proveedor NUMBER(10) PRIMARY KEY,
    Nombre_Proveedor NVARCHAR2(200) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_PROV_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_PROVEEDORES_BI
BEFORE INSERT ON FIDE_Proveedores_TB FOR EACH ROW
BEGIN SELECT SEQ_PROVEEDORES.NEXTVAL INTO :NEW.ID_Proveedor FROM DUAL; END;
/

-- Tabla Usuarios
CREATE TABLE FIDE_Usuarios_TB (
    ID_Usuario NUMBER(10) PRIMARY KEY,
    Nombre NVARCHAR2(100) NOT NULL,
    Apellido_Paterno NVARCHAR2(100) NOT NULL,
    Apellido_Materno NVARCHAR2(100),
    Contrasenna NVARCHAR2(255) NOT NULL,
    Fecha_Creacion DATE NOT NULL,
    ID_Rol NUMBER(10) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_USR_ROL FOREIGN KEY (ID_Rol) REFERENCES FIDE_Roles_TB(ID_Rol),
    CONSTRAINT FK_USR_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_USUARIOS_BI
BEFORE INSERT ON FIDE_Usuarios_TB FOR EACH ROW
BEGIN SELECT SEQ_USUARIOS.NEXTVAL INTO :NEW.ID_Usuario FROM DUAL; END;
/

-- Tabla Correo_Usuarios
CREATE TABLE FIDE_Correo_Usuarios_TB (
    ID_Usuario NUMBER(10) NOT NULL,
    Correo NVARCHAR2(100) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT PK_CORREO_USR PRIMARY KEY (ID_Usuario, Correo),
    CONSTRAINT FK_CORREO_USR_USR FOREIGN KEY (ID_Usuario) REFERENCES FIDE_Usuarios_TB(ID_Usuario),
    CONSTRAINT FK_CORREO_USR_EST FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);

-- Tabla Telefonos_Usuarios
CREATE TABLE FIDE_Telefonos_Usuarios_TB (
    ID_Usuario NUMBER(10) NOT NULL,
    Telefono NVARCHAR2(20) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT PK_TEL_USR PRIMARY KEY (ID_Usuario, Telefono),
    CONSTRAINT FK_TEL_USR_USR FOREIGN KEY (ID_Usuario) REFERENCES FIDE_Usuarios_TB(ID_Usuario),
    CONSTRAINT FK_TEL_USR_EST FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);

-- Tabla Productos
CREATE TABLE FIDE_Productos_TB (
    ID_Producto NUMBER(10) PRIMARY KEY,
    Codigo NVARCHAR2(50) NOT NULL,
    ID_Categoria NUMBER(10) NOT NULL,
    Nombre_Producto NVARCHAR2(100) NOT NULL,
    Precio_Venta NUMBER(10,2) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_PROD_CAT FOREIGN KEY (ID_Categoria) REFERENCES FIDE_Categorias_TB(ID_Categoria),
    CONSTRAINT FK_PROD_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_PRODUCTOS_BI
BEFORE INSERT ON FIDE_Productos_TB FOR EACH ROW
BEGIN SELECT SEQ_PRODUCTOS.NEXTVAL INTO :NEW.ID_Producto FROM DUAL; END;
/

-- Tabla Insumos
CREATE TABLE FIDE_Insumos_TB (
    ID_Insumo NUMBER(10) PRIMARY KEY,
    Nombre_Insumo NVARCHAR2(100) NOT NULL,
    Stock NUMBER(10) NOT NULL,
    ID_Unidad_Medida NUMBER(10) NOT NULL,
    ID_Categoria NUMBER(10) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_INS_UNIDAD FOREIGN KEY (ID_Unidad_Medida) REFERENCES FIDE_Unidades_Medidas_TB(ID_Unidad_Medida),
    CONSTRAINT FK_INS_CAT FOREIGN KEY (ID_Categoria) REFERENCES FIDE_Categorias_TB(ID_Categoria),
    CONSTRAINT FK_INS_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_INSUMOS_BI
BEFORE INSERT ON FIDE_Insumos_TB FOR EACH ROW
BEGIN SELECT SEQ_INSUMOS.NEXTVAL INTO :NEW.ID_Insumo FROM DUAL; END;
/

-- Tabla Inventario_Item
CREATE TABLE FIDE_Inventario_Item_TB (
    ID_Inventario_Item NUMBER(10) PRIMARY KEY,
    ID_Producto NUMBER(10) NULL,
    ID_Insumo NUMBER(10) NULL,
    Stock NUMBER(10) NOT NULL,
    Stock_Minimo NUMBER(10) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_INV_PROD FOREIGN KEY (ID_Producto) REFERENCES FIDE_Productos_TB(ID_Producto),
    CONSTRAINT FK_INV_INS FOREIGN KEY (ID_Insumo) REFERENCES FIDE_Insumos_TB(ID_Insumo),
    CONSTRAINT FK_INV_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_INVENTARIO_BI
BEFORE INSERT ON FIDE_Inventario_Item_TB FOR EACH ROW
BEGIN SELECT SEQ_INVENTARIO_ITEM.NEXTVAL INTO :NEW.ID_Inventario_Item FROM DUAL; END;
/

-- Tabla Movimiento_Inventario
CREATE TABLE FIDE_Movimiento_Inventario_TB (
    ID_Movimiento NUMBER(10) PRIMARY KEY,
    ID_Inventario_Item NUMBER(10) NOT NULL,
    ID_Tipo NUMBER(10) NOT NULL,
    Fecha_Hora_Movimiento TIMESTAMP NOT NULL,
    Cantidad NUMBER(10) NOT NULL,
    ID_Referencia_Tabla NUMBER(10) NOT NULL,
    Referencia_Id NUMBER(10) NOT NULL,
    ID_Usuario NUMBER(10) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_MOV_INV_ITEM FOREIGN KEY (ID_Inventario_Item) REFERENCES FIDE_Inventario_Item_TB(ID_Inventario_Item),
    CONSTRAINT FK_MOV_TIPO FOREIGN KEY (ID_Tipo) REFERENCES FIDE_Tipo_TB(ID_Tipo),
    CONSTRAINT FK_MOV_REF FOREIGN KEY (ID_Referencia_Tabla) REFERENCES FIDE_Referencia_Tabla_TB(ID_Referencia_Tabla),
    CONSTRAINT FK_MOV_USR FOREIGN KEY (ID_Usuario) REFERENCES FIDE_Usuarios_TB(ID_Usuario),
    CONSTRAINT FK_MOV_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_MOVIMIENTO_BI
BEFORE INSERT ON FIDE_Movimiento_Inventario_TB FOR EACH ROW
BEGIN SELECT SEQ_MOVIMIENTO.NEXTVAL INTO :NEW.ID_Movimiento FROM DUAL; END;
/

-- Tabla Venta
CREATE TABLE FIDE_Venta_TB (
    ID_Venta NUMBER(10) PRIMARY KEY,
    ID_Usuario NUMBER(10) NOT NULL,
    Fecha_Hora_Venta TIMESTAMP NOT NULL,
    Total_Venta NUMBER(10,2) NOT NULL,
    ID_Metodo_Pago NUMBER(10) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_VTA_USR FOREIGN KEY (ID_Usuario) REFERENCES FIDE_Usuarios_TB(ID_Usuario),
    CONSTRAINT FK_VTA_METODO FOREIGN KEY (ID_Metodo_Pago) REFERENCES FIDE_Metodos_Pago_TB(ID_Metodo_Pago),
    CONSTRAINT FK_VTA_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_VENTA_BI
BEFORE INSERT ON FIDE_Venta_TB FOR EACH ROW
BEGIN SELECT SEQ_VENTA.NEXTVAL INTO :NEW.ID_Venta FROM DUAL; END;
/

-- Tabla Venta_Productos
CREATE TABLE FIDE_Venta_Productos_TB (
    ID_Venta NUMBER(10) NOT NULL,
    ID_Producto NUMBER(10) NOT NULL,
    Cantidad NUMBER(10) NOT NULL,
    Precio_Unitario NUMBER(10,2) NOT NULL,
    Subtotal_Venta NUMBER(10,2) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT PK_VTA_PROD PRIMARY KEY (ID_Venta, ID_Producto),
    CONSTRAINT FK_VTAPROD_VTA FOREIGN KEY (ID_Venta) REFERENCES FIDE_Venta_TB(ID_Venta),
    CONSTRAINT FK_VTAPROD_PROD FOREIGN KEY (ID_Producto) REFERENCES FIDE_Productos_TB(ID_Producto),
    CONSTRAINT FK_VTAPROD_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);

-- Tabla Recetas
CREATE TABLE FIDE_Recetas_TB (
    ID_Receta NUMBER(10) PRIMARY KEY,
    ID_Producto NUMBER(10) NOT NULL,
    Rendimiento NUMBER(10) NOT NULL,
    Notas NVARCHAR2(400),
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_REC_PROD FOREIGN KEY (ID_Producto) REFERENCES FIDE_Productos_TB(ID_Producto),
    CONSTRAINT FK_REC_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_RECETAS_BI
BEFORE INSERT ON FIDE_Recetas_TB FOR EACH ROW
BEGIN SELECT SEQ_RECETAS.NEXTVAL INTO :NEW.ID_Receta FROM DUAL; END;
/

-- Tabla Receta_Insumo
CREATE TABLE FIDE_Receta_Insumo_TB (
    ID_Receta NUMBER(10) NOT NULL,
    ID_Insumo NUMBER(10) NOT NULL,
    Cantidades NUMBER(10,2) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT PK_REC_INS PRIMARY KEY (ID_Receta, ID_Insumo),
    CONSTRAINT FK_RECINS_REC FOREIGN KEY (ID_Receta) REFERENCES FIDE_Recetas_TB(ID_Receta),
    CONSTRAINT FK_RECINS_INS FOREIGN KEY (ID_Insumo) REFERENCES FIDE_Insumos_TB(ID_Insumo),
    CONSTRAINT FK_RECINS_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);

-- Tabla Compras
CREATE TABLE FIDE_Compras_TB (
    ID_Compra NUMBER(10) PRIMARY KEY,
    ID_Proveedor NUMBER(10) NOT NULL,
    ID_Usuario NUMBER(10) NOT NULL,
    Fecha_Hora_Compra TIMESTAMP NOT NULL,
    Total_Compra NUMBER(10,2) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_COMP_PROV FOREIGN KEY (ID_Proveedor) REFERENCES FIDE_Proveedores_TB(ID_Proveedor),
    CONSTRAINT FK_COMP_USR FOREIGN KEY (ID_Usuario) REFERENCES FIDE_Usuarios_TB(ID_Usuario),
    CONSTRAINT FK_COMP_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_COMPRAS_BI
BEFORE INSERT ON FIDE_Compras_TB FOR EACH ROW
BEGIN SELECT SEQ_COMPRAS.NEXTVAL INTO :NEW.ID_Compra FROM DUAL; END;
/

-- Tabla Compras_Insumos
CREATE TABLE FIDE_Compras_Insumos_TB (
    ID_Compra NUMBER(10) NOT NULL,
    ID_Insumo NUMBER(10) NOT NULL,
    Cantidad NUMBER(10) NOT NULL,
    Precio_Unid NUMBER(10,2) NOT NULL,
    Subtotal_Compra NUMBER(10,2) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT PK_COMP_INS PRIMARY KEY (ID_Compra, ID_Insumo),
    CONSTRAINT FK_COMPINS_COMP FOREIGN KEY (ID_Compra) REFERENCES FIDE_Compras_TB(ID_Compra),
    CONSTRAINT FK_COMPINS_INS FOREIGN KEY (ID_Insumo) REFERENCES FIDE_Insumos_TB(ID_Insumo),
    CONSTRAINT FK_COMPINS_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);

-- Tabla Orden_Produccion
CREATE TABLE FIDE_Orden_Produccion_TB (
    ID_Orden_Produccion NUMBER(10) PRIMARY KEY,
    ID_Usuario NUMBER(10) NOT NULL,
    Fecha_Hora TIMESTAMP NOT NULL,
    Observaciones NVARCHAR2(400),
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_ORD_USR FOREIGN KEY (ID_Usuario) REFERENCES FIDE_Usuarios_TB(ID_Usuario),
    CONSTRAINT FK_ORD_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_ORDEN_PROD_BI
BEFORE INSERT ON FIDE_Orden_Produccion_TB FOR EACH ROW
BEGIN SELECT SEQ_ORDEN_PROD.NEXTVAL INTO :NEW.ID_Orden_Produccion FROM DUAL; END;
/

-- Tabla Orden_Detalle
CREATE TABLE FIDE_Orden_Detalle_TB (
    ID_Orden_Produccion NUMBER(10) NOT NULL,
    ID_Producto NUMBER(10) NOT NULL,
    Cantidad_Ordenada NUMBER(10) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT PK_ORD_DET PRIMARY KEY (ID_Orden_Produccion, ID_Producto),
    CONSTRAINT FK_ORDDET_ORD FOREIGN KEY (ID_Orden_Produccion) REFERENCES FIDE_Orden_Produccion_TB(ID_Orden_Produccion),
    CONSTRAINT FK_ORDDET_PROD FOREIGN KEY (ID_Producto) REFERENCES FIDE_Productos_TB(ID_Producto),
    CONSTRAINT FK_ORDDET_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);

-- Tabla Orden_Insumo
CREATE TABLE FIDE_Orden_Insumo_TB (
    ID_Orden_Produccion NUMBER(10) NOT NULL,
    ID_Insumo NUMBER(10) NOT NULL,
    Cantidad_Usada NUMBER(10,2) NOT NULL,
    CONSTRAINT PK_ORD_INS PRIMARY KEY (ID_Orden_Produccion, ID_Insumo),
    CONSTRAINT FK_ORDINS_ORD FOREIGN KEY (ID_Orden_Produccion) REFERENCES FIDE_Orden_Produccion_TB(ID_Orden_Produccion),
    CONSTRAINT FK_ORDINS_INS FOREIGN KEY (ID_Insumo) REFERENCES FIDE_Insumos_TB(ID_Insumo)
);

-- Tabla Correo_Proveedores
CREATE TABLE FIDE_Correo_Proveedores_TB (
    ID_Proveedor NUMBER(10) NOT NULL,
    Correo NVARCHAR2(100) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT PK_CORREO_PROV PRIMARY KEY (ID_Proveedor, Correo),
    CONSTRAINT FK_CORREOPROV_PROV FOREIGN KEY (ID_Proveedor) REFERENCES FIDE_Proveedores_TB(ID_Proveedor),
    CONSTRAINT FK_CORREOPROV_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);

-- Tabla Telefono_Proveedor
CREATE TABLE FIDE_Telefono_Proveedor_TB (
    ID_Proveedor NUMBER(10) NOT NULL,
    Telefono NVARCHAR2(20) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT PK_TEL_PROV PRIMARY KEY (ID_Proveedor, Telefono),
    CONSTRAINT FK_TELPROV_PROV FOREIGN KEY (ID_Proveedor) REFERENCES FIDE_Proveedores_TB(ID_Proveedor),
    CONSTRAINT FK_TELPROV_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);

-- Tabla Factura
CREATE TABLE FIDE_Factura_TB (
    ID_Factura NUMBER(10) PRIMARY KEY,
    Numero_Factura NVARCHAR2(50) NOT NULL,
    ID_Venta NUMBER(10) NOT NULL,
    Fecha_Emision DATE NOT NULL,
    Total_Factura NUMBER(10,2) NOT NULL,
    ID_Estado NUMBER(10) NOT NULL,
    CONSTRAINT FK_FACT_VTA FOREIGN KEY (ID_Venta) REFERENCES FIDE_Venta_TB(ID_Venta),
    CONSTRAINT FK_FACT_ESTADO FOREIGN KEY (ID_Estado) REFERENCES FIDE_Estados_TB(ID_Estado)
);
CREATE OR REPLACE TRIGGER TRG_FACTURA_BI
BEFORE INSERT ON FIDE_Factura_TB FOR EACH ROW
BEGIN SELECT SEQ_FACTURA.NEXTVAL INTO :NEW.ID_Factura FROM DUAL; END;
